version: 2

sources:
  - name: public       # Das Datenbank-Schema, in dem raw_weather liegt
    schema: public
    tables:
      - name: raw_weather
      - name: raw_stops
      - name: raw_routes
      - name: raw_trips
      - name: raw_stop_times
      - name: raw_calendar
